# Generated by Django 5.2.1 on 2025-05-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
